<?php
/**
 * CONFIG EXAMPLE - REFERENCE ONLY
 * 
 * DO NOT EDIT THIS FILE!
 * This is example configuration file for reference.
 * 
 * Actual configuration is in: includes/config.php
 */

// ============================================
// DATABASE CONFIGURATION
// ============================================

// Jika local (XAMPP) - gunakan ini:
define('DB_HOST', 'localhost');
define('DB_USER', 'root');
define('DB_PASS', '');                    // Biasanya kosong untuk localhost
define('DB_NAME', 'portfolio_db');

// Jika ada password MySQL:
// define('DB_PASS', 'password123');

// Jika hosting (contoh Niagahoster):
// define('DB_HOST', 'localhost');
// define('DB_USER', 'username_db');
// define('DB_PASS', 'password_db_yang_kuat');
// define('DB_NAME', 'username_portfolio_db');

// ============================================
// URL CONFIGURATION
// ============================================

// Local development
define('BASE_URL', 'http://localhost/webset01/portfolio/');

// Hosting dengan domain
// define('BASE_URL', 'https://nanangkhasan.com/');

// Hosting dengan subdomain
// define('BASE_URL', 'https://portfolio.nanangkhasan.com/');

// Hosting dengan subfolder
// define('BASE_URL', 'https://example.com/portfolio/');

define('ASSETS_URL', BASE_URL . 'assets/');

// ============================================
// TIMEZONE
// ============================================

date_default_timezone_set('Asia/Jakarta');
// Opsi timezone lain:
// 'America/New_York'
// 'Europe/London'
// 'Asia/Tokyo'
// 'Australia/Sydney'

// ============================================
// SESSION
// ============================================

session_start();

// Optional: Session configuration
// session_set_cookie_params([
//     'lifetime' => 86400,        // 24 hours
//     'path' => '/',
//     'domain' => 'localhost',
//     'secure' => false,          // true jika HTTPS
//     'httponly' => true,
// ]);

// ============================================
// ERROR REPORTING
// ============================================

// Development - tampilkan semua error
error_reporting(E_ALL);
ini_set('display_errors', 1);

// Production - jangan tampilkan error
// error_reporting(E_ALL);
// ini_set('display_errors', 0);
// ini_set('log_errors', 1);
// ini_set('error_log', '/path/to/error.log');

// ============================================
// DEBUG MODE
// ============================================

define('DEBUG', true);          // true = development, false = production

// ============================================
// APPLICATION CONSTANTS
// ============================================

// Paths
define('ROOT_PATH', __DIR__);
define('INCLUDES_PATH', ROOT_PATH . '/includes/');
define('PAGES_PATH', ROOT_PATH . '/pages/');
define('ADMIN_PATH', ROOT_PATH . '/admin/');

// Site info
define('SITE_NAME', 'Nanang Khasan Bisri');
define('SITE_TITLE', 'Portfolio - ' . SITE_NAME);
define('ADMIN_EMAIL', 'admin@example.com');

// ============================================
// DATABASE CONNECTION EXAMPLE
// ============================================

/*
// Connection using mysqli
$conn = new mysqli(DB_HOST, DB_USER, DB_PASS, DB_NAME);

// Check connection
if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
}

// Set charset
$conn->set_charset("utf8mb4");

// Connection using PDO (alternative)
try {
    $pdo = new PDO(
        "mysql:host=" . DB_HOST . ";dbname=" . DB_NAME,
        DB_USER,
        DB_PASS,
        array(PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION)
    );
} catch(PDOException $e) {
    echo "Connection error: " . $e->getMessage();
}
*/

// ============================================
// SECURITY HEADERS (optional)
// ============================================

/*
// Di awal file (sebelum output apapun)
header('X-Content-Type-Options: nosniff');
header('X-Frame-Options: SAMEORIGIN');
header('X-XSS-Protection: 1; mode=block');
header('Referrer-Policy: strict-origin-when-cross-origin');

// Jika HTTPS
// header('Strict-Transport-Security: max-age=31536000; includeSubDomains');
*/

// ============================================
// EMAIL CONFIGURATION (untuk nantinya)
// ============================================

/*
// SMTP Configuration
define('MAIL_HOST', 'smtp.gmail.com');
define('MAIL_PORT', 587);
define('MAIL_USERNAME', 'your-email@gmail.com');
define('MAIL_PASSWORD', 'your-app-password');
define('MAIL_FROM', 'noreply@nanangkhasan.com');
define('MAIL_FROM_NAME', 'Nanang Khasan');

// Gunakan dengan PHPMailer atau SwiftMailer
*/

// ============================================
// LOGGING (untuk tracking)
// ============================================

/*
// Log directory
define('LOG_PATH', ROOT_PATH . '/logs/');

// Log level
define('LOG_LEVEL', 'INFO');  // DEBUG, INFO, WARNING, ERROR

// Log to file
function logMessage($level, $message) {
    $logFile = LOG_PATH . date('Y-m-d') . '.log';
    $timestamp = date('Y-m-d H:i:s');
    $logMessage = "[{$timestamp}] [{$level}] {$message}\n";
    error_log($logMessage, 3, $logFile);
}
*/

// ============================================
// CACHE CONFIGURATION (untuk nantinya)
// ============================================

/*
// Redis Cache
define('CACHE_HOST', 'localhost');
define('CACHE_PORT', 6379);
define('CACHE_TTL', 3600);  // 1 hour

// File Cache
define('CACHE_DIR', ROOT_PATH . '/cache/');
*/

// ============================================
// API KEYS (untuk nantinya)
// ============================================

/*
define('GOOGLE_API_KEY', 'your-google-api-key');
define('GITHUB_API_TOKEN', 'your-github-token');
define('STRIPE_KEY', 'your-stripe-key');
*/

// ============================================
// ENVIRONMENT VARIABLES (alternative)
// ============================================

/*
// Load .env file
function loadEnv() {
    $envFile = ROOT_PATH . '/.env';
    if (file_exists($envFile)) {
        $lines = file($envFile, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES);
        foreach ($lines as $line) {
            if (strpos($line, '=') !== false && strpos($line, '#') !== 0) {
                list($key, $value) = explode('=', $line, 2);
                putenv(trim($key) . '=' . trim($value));
            }
        }
    }
}

loadEnv();

// Usage: getenv('DB_HOST')
*/

// ============================================
// END OF CONFIGURATION
// ============================================

?>
